services:
  frontend:
    build: ./frontend 
    ports:
      - "80:80" 
    depends_on:
      - backend 
    networks:
      - maritime-network 

  backend:
    build: ./backend 
    ports:
      - "4000:4000" 
    networks:
      - maritime-network

networks:
  maritime-network: 
    driver: bridge